# Generated by Django 3.2.4 on 2022-02-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='userpw',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
