# Generated by Django 4.0.2 on 2022-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='consecutiveHighR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='consecutiveHighW',
            field=models.IntegerField(default=0),
        ),
    ]
