# Generated by Django 3.2.4 on 2022-02-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_remove_userss_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='userpw2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
