# Generated by Django 3.2.4 on 2022-02-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20220207_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
