# Generated by Django 3.2.4 on 2022-02-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_auto_20220207_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_status',
            name='user_id',
        ),
        migrations.AddField(
            model_name='machine_status',
            name='stat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
