# Generated by Django 3.2.4 on 2022-02-09 13:02

from django.db import migrations, models
import test1.models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_auto_20220207_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('idealStudyTime', models.CharField(max_length=20)),
                ('audioVideoHighAttention', models.CharField(max_length=20)),
                ('readWriteHighAttention', models.CharField(max_length=20)),
                ('sessionsCompletedAV', models.CharField(max_length=20)),
                ('sessionsCompletedRW', models.CharField(max_length=20)),
                ('highToTotalAV', models.CharField(max_length=20)),
                ('highToTotalRW', models.CharField(max_length=20)),
                ('graphHighAttention', models.CharField(max_length=20)),
                ('graphLowAttention', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', test1.models.UserManager()),
            ],
        ),
    ]
