# Generated by Django 3.2.4 on 2022-02-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_auto_20220209_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userss',
        ),
    ]
